name: e-paper
description: A driver for some popular E-paper displays.
environment:
  sdk: ^2.0.0-alpha.118
dependencies:
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^2.1.0
